# Generated by Django 2.2 on 2019-05-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0, verbose_name='灯杆号')),
                ('s_voltage', models.FloatField(default=0.0, verbose_name='太阳能板电压')),
                ('s_current', models.FloatField(default=0.0, verbose_name='太阳能板电流')),
                ('b_voltage', models.FloatField(default=0.0, verbose_name='=蓄电池电压')),
                ('charging_status', models.SmallIntegerField(default=0, verbose_name='充电工作状态')),
                ('load_current', models.FloatField(default=0.0, verbose_name='负载电压')),
                ('load_voltage', models.FloatField(default=0.0, verbose_name='负载电压')),
                ('lamp_status', models.SmallIntegerField(default=0, verbose_name='开灯状态')),
                ('work_time', models.FloatField(default=0.0, verbose_name='工作时间')),
                ('cumulative_power', models.FloatField(default=0.0, verbose_name='累计电量')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': 'solar',
                'verbose_name_plural': 'solar',
                'ordering': ['-c_time'],
            },
        ),
    ]
